name: EprepagApp

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile_dev
    extra_hosts:
      - "dev.e-prepag.com.br:127.0.0.1"
      - "backoffice-dev.e-prepag.com.br:127.0.0.1"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - eprepag_net
    volumes:
      - ./www:/www
      - ./docker-config/certs_local:/etc/apache2/certs
      - ./www/arquivos_gerados:/www/arquivos_gerados
      - ./docker-config/apache_conf/security.conf:/etc/apache2/conf-enabled/security.conf:ro
    env_file:
      - ./www/.env
    environment:
      TZ: "America/Fortaleza"

  assinador:
    build: ./assinador-dotnet
    container_name: assinador-dotnet
    networks:
      - eprepag_net
    ports:
      - "5000:5000"
    volumes:
      - ./certs:/certs:ro           # Acesso ao certificado (read-only)
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      TZ: "America/Fortaleza"
    restart: unless-stopped

networks:
  eprepag_net:
    driver: bridge