FROM php:8.4-apache

RUN set -eux; \
    a2enmod rewrite ssl; \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        libzip-dev \
        zlib1g-dev \
        libpq-dev \
        ca-certificates \
        curl \
        libcurl4-openssl-dev \
        libjpeg62-turbo-dev \
        libpng-dev \
        libfreetype6-dev \
        libxml2-dev \
    ; \
    docker-php-ext-configure gd --with-freetype --with-jpeg; \
    docker-php-ext-install -j"$(nproc)" \
        zip \
        mysqli \
        pgsql \
        pdo_pgsql \
        curl \
        pdo_mysql \
        gd \
    ; \
    update-ca-certificates; \
    rm -rf /var/lib/apt/lists/*

WORKDIR /www

RUN groupadd -g 1001 eprepagadm \
    && useradd -u 1001 -g eprepagadm -ms /bin/bash eprepagadm

RUN sed -i 's/www-data/eprepagadm/g' /etc/apache2/envvars

RUN rm -f /etc/apache2/sites-enabled/000-default.conf
COPY ./docker-config/apache_conf/dev/*.conf /etc/apache2/sites-enabled/

RUN printf '%s\n' \
    'SetEnv HOME /www/public_html/' \
    'SetEnv USER eprepagadm' \
    'SetEnv SSL_TLS_SNI localhost' \
    >> /etc/apache2/conf-enabled/environment.conf

COPY ./docker-config/php/php.ini /usr/local/etc/php/