<?php
// tb_venda_games usa vg_pagto_tipo::smallint
// tb_pag_compras usa iforma::char(1)
function getCodigoNumericoParaPagto($iforma) {

	$numeric_code = "0";
	switch($iforma) {
		case $GLOBALS['FORMAS_PAGAMENTO']['DEP_DOC_TRANSF']:
		case $GLOBALS['FORMAS_PAGAMENTO']['BOLETO_BANCARIO']:
		case $GLOBALS['FORMAS_PAGAMENTO']['TRANSFERENCIA_ENTRE_CONTAS_BRADESCO']:
		case $GLOBALS['FORMAS_PAGAMENTO']['PAGAMENTO_FACIL_BRADESCO_DEBITO']:
		case $GLOBALS['FORMAS_PAGAMENTO']['PAGAMENTO_FACIL_BRADESCO_CREDITO']:
		case $GLOBALS['FORMAS_PAGAMENTO']['PAGAMENTO_BB_DEBITO_SUA_CONTA']:
			$numeric_code = $iforma;
			break;

		case $GLOBALS['FORMAS_PAGAMENTO']['PAGAMENTO_PIX']:
		case $GLOBALS['PAGAMENTO_PIX_NUMERIC']:
			$numeric_code = $GLOBALS['PAGAMENTO_PIX_NUMERIC'];
			break;

		case $GLOBALS['FORMAS_PAGAMENTO']['PAGAMENTO_BANCO_ITAU_ONLINE']:
		case $GLOBALS['PAGAMENTO_BANCO_ITAU_ONLINE_NUMERIC']:
			$numeric_code = $GLOBALS['PAGAMENTO_BANCO_ITAU_ONLINE_NUMERIC'];
			break;
		case $GLOBALS['FORMAS_PAGAMENTO']['PAGAMENTO_PIN_EPREPAG']:
		case $GLOBALS['PAGAMENTO_PIN_EPREPAG_NUMERIC']:
			$numeric_code = $GLOBALS['PAGAMENTO_PIN_EPREPAG_NUMERIC'];
			break;
		case $GLOBALS['FORMAS_PAGAMENTO']['PAGAMENTO_HIPAY_ONLINE']:
		case $GLOBALS['PAGAMENTO_HIPAY_ONLINE_NUMERIC']:
			$numeric_code = $GLOBALS['PAGAMENTO_HIPAY_ONLINE_NUMERIC'];
			break;
		case $GLOBALS['FORMAS_PAGAMENTO']['PAGAMENTO_PAYPAL_ONLINE']:
		case $GLOBALS['PAGAMENTO_PAYPAL_ONLINE_NUMERIC']:
			$numeric_code = $GLOBALS['PAGAMENTO_PAYPAL_ONLINE_NUMERIC'];
			break;
		case $GLOBALS['PAGAMENTO_BANCO_EPP_ONLINE']:
		case $GLOBALS['PAGAMENTO_BANCO_EPP_ONLINE_NUMERIC']:
			$numeric_code = $GLOBALS['PAGAMENTO_BANCO_EPP_ONLINE_NUMERIC'];
			break;
		case $GLOBALS['FORMAS_PAGAMENTO']['PAGAMENTO_MCOIN']:
		case $GLOBALS['PAGAMENTO_MCOIN_NUMERIC']:
			$numeric_code = $GLOBALS['PAGAMENTO_MCOIN_NUMERIC'];
			break;

		case $GLOBALS['FORMAS_PAGAMENTO']['OFERTAS']:
		case $GLOBALS['PAGAMENTO_OFERTAS_NUMERIC']:
			$numeric_code = $GLOBALS['PAGAMENTO_OFERTAS_NUMERIC'];
			break;

	}
	return $numeric_code;
}

// tb_venda_games usa vg_pagto_tipo::smallint
// tb_pag_compras usa iforma::char(1)
function getCodigoCaracterParaPagto($iforma) {

	$character_code = "";
	switch($iforma) {
		case $GLOBALS['FORMAS_PAGAMENTO']['DEP_DOC_TRANSF']:
		case $GLOBALS['FORMAS_PAGAMENTO']['BOLETO_BANCARIO']:
		case $GLOBALS['FORMAS_PAGAMENTO']['TRANSFERENCIA_ENTRE_CONTAS_BRADESCO']:
		case $GLOBALS['FORMAS_PAGAMENTO']['PAGAMENTO_FACIL_BRADESCO_DEBITO']:
		case $GLOBALS['FORMAS_PAGAMENTO']['PAGAMENTO_FACIL_BRADESCO_CREDITO']:
		case $GLOBALS['FORMAS_PAGAMENTO']['PAGAMENTO_BB_DEBITO_SUA_CONTA']:
			$character_code = $iforma;
			break;
		case $GLOBALS['FORMAS_PAGAMENTO']['PAGAMENTO_BANCO_ITAU_ONLINE']:
		case $GLOBALS['PAGAMENTO_BANCO_ITAU_ONLINE_NUMERIC']:
			$character_code = $GLOBALS['FORMAS_PAGAMENTO']['PAGAMENTO_BANCO_ITAU_ONLINE'];
			break;
		case $GLOBALS['FORMAS_PAGAMENTO']['PAGAMENTO_PIN_EPREPAG']:
		case $GLOBALS['PAGAMENTO_PIN_EPREPAG_NUMERIC']:
			$character_code = $GLOBALS['FORMAS_PAGAMENTO']['PAGAMENTO_PIN_EPREPAG'];
			break;
		case $GLOBALS['FORMAS_PAGAMENTO']['PAGAMENTO_HIPAY_ONLINE']:
		case $GLOBALS['PAGAMENTO_HIPAY_ONLINE_NUMERIC']:
			$character_code = $GLOBALS['FORMAS_PAGAMENTO']['PAGAMENTO_HIPAY_ONLINE'];
			break;
		case $GLOBALS['FORMAS_PAGAMENTO']['PAGAMENTO_PAYPAL_ONLINE']:
		case $GLOBALS['PAGAMENTO_PAYPAL_ONLINE_NUMERIC']:
			$character_code = $GLOBALS['FORMAS_PAGAMENTO']['PAGAMENTO_PAYPAL_ONLINE'];
			break;
		case $GLOBALS['PAGAMENTO_BANCO_EPP_ONLINE']:
		case $GLOBALS['PAGAMENTO_BANCO_EPP_ONLINE_NUMERIC']:
			$character_code = $GLOBALS['PAGAMENTO_BANCO_EPP_ONLINE'];
			break;
		case $GLOBALS['FORMAS_PAGAMENTO']['OFERTAS']:
		case $GLOBALS['PAGAMENTO_OFERTAS_NUMERIC']:
			$character_code = $GLOBALS['FORMAS_PAGAMENTO']['OFERTAS'];
			break;
		case $GLOBALS['FORMAS_PAGAMENTO']['PAGAMENTO_MCOIN']:
		case $GLOBALS['PAGAMENTO_MCOIN_NUMERIC']:
			$character_code = $GLOBALS['FORMAS_PAGAMENTO']['PAGAMENTO_MCOIN'];
			break;
                case $GLOBALS['FORMAS_PAGAMENTO']['PAGAMENTO_PIX']:
		case $GLOBALS['PAGAMENTO_PIX_NUMERIC']:
			$character_code = $GLOBALS['FORMAS_PAGAMENTO']['PAGAMENTO_PIX'];
			break;

	}
	return $character_code;
}


?>