server {
    listen 80;
    listen 443 ssl;
    server_name localhost;

    # Ocultar versão do Nginx (Segurança)
    server_tokens off;

    # --- CONFIGURAÇÃO SSL (AUTO-ASSINADO) ---
    # Comente estas linhas quando for usar Cloudflare Tunnel
    ssl_certificate /etc/nginx/certs/nginx-selfsigned.crt;
    ssl_certificate_key /etc/nginx/certs/nginx-selfsigned.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    root /www/public_html;
    index index.php index.html;

    # Cabeçalhos de Segurança
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Bloquear acesso a arquivos sensíveis
    location ~ /\.(?!well-known).* {
        deny all;
    }

    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_param SCRIPT_FILENAME /www/public_html$fastcgi_script_name;
        include fastcgi_params;
        
        # Passar informação de HTTPS para o PHP
        fastcgi_param HTTPS $https if_not_empty;
        
        fastcgi_hide_header X-Powered-By;
        fastcgi_buffer_size 128k;
        fastcgi_buffers 4 256k;
        fastcgi_busy_buffers_size 256k;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires max;
        log_not_found off;
    }
}
